name: Removal
description: Suggest the removal an existing entry
title: '[REMOVAL] <title>'
labels: ['Suggested Removal', 'Awaiting Review']
assignees:
  - lissy93
body:
  # Title
  - type: input
    id: service-title
    attributes:
      label: Title
      description: >-
        The name of the project this ticket refers to. Should match how it is written on the list
      placeholder: e.g. KeePass
    validations:
      required: true

  # Removal description
  - type: textarea
    id: removal-reason
    attributes:
      label: Removal Reason
      description: |
        Describe why this project should be removed.
        Please backup your argument with relevant and accurate info, and link to references from reputable sources. 
    validations:
      required: true

  # Optional, removal data (auto-filled from awesome-privacy.xyz)
  - type: textarea
    id: removal-data
    attributes:
      label: Removal Data
      render: yaml
      placeholder: |
        You do not need to fill this section in, if you're manually submitting this removal request.
        For users submitting via awesome-privacy.xyz this will be auto-filled.
    validations:
      required: false

  # Association disclosure
  - type: input
    id: association
    attributes:
      label: Association Disclosure
      description: >-
        For transparency, please state if you currently / previously have had any affiliation with
        either this project, or another project within a similar industry / category
    validations:
      required: false

  # Can user submit PR
  - type: dropdown
    id: canImplement
    attributes:
      label: Would you like to submit a PR?
      description: Is this removal something that you are willing to submit a pull request for?
      options:
        - 'No.'
        - 'Maybe?'
        - 'Yes!'
    validations:
      required: false

  # Confirmation checkboxes
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: "Before submitting, please ensure that:"
      options:
        - label: You have filled out this form accurately, and to the best of your knowledge
          required: true
        - label: You have indicated whether or not you are associated with this project or a competitor
          required: true
        - label: A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
          required: true
        - label: You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
          required: true
        - label: You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  
  # Final message
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        <img align="left" width="160" src="https://i.ibb.co/S5vCnhL/gh-thanks.gif" alt="🐙" />
        Thank you for your suggested removal! You should expect a reply within 48 hours.<br>
        ⭐️ Consider dropping the repo a star if you're enjoying Awesome-Privacy.<br>

