
name = "awesome-privacy-api"
compatibility_date = "2024-03-04"
main = "src/index.ts"

rules = [
  { type = "Text", globs = ["public/*.html"], fallthrough = true }
]


[site]
bucket = "./public"  # Path to your static files

