# Checks newly opened issues contain enough info, and follow the required format
name: 🎫 Issue Validator
on:
  issues:
    types: [opened]
jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Default
        if: "endsWith(github.event.issue.title, '<title>')"
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            Hello ${{ github.event.actor }} :wave:
            Please ensure that your ticket has an appropriate title
