npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ECB95473-FBAF-463F-905C-C9ED4C00D519
  awesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ECB95473-FBAF-463F-905C-C9ED4C00D519
